version: '3'

services:
  client:
    command: npm run serve
    image: node:16-alpine
    environment:
      HOST: 0.0.0.0
      NODE_ENV: development
      PORT: 8080
      VUE_APP_AGORA_APP_ID: $AGORA_APP_ID
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    working_dir: /app
